language: r
cache: packages
sudo: true
dist: trusty

env: _R_CHECK_CRAN_INCOMING_=FALSE


addons:
  apt:
    packages:
      - R

r_packages:
  - covr
  - devtools
  - raster
  - rgdal
  - Rcpp

after_success:
  - Rscript -e 'library(covr); codecov()'

script:
  - R -e "source('test/popstest2x2.R'); data;"