language: r

env: _R_CHECK_CRAN_INCOMING_=FALSE

r:
  - oldrel
  - release
  - devel

# install dependencies
addons:
  apt:
    packages:
      - R

r_packages:
  - covr
  - devtools
  - raster
  - rgdal
  - Rcpp

after_success:
  - Rscript -e 'library(covr); codecov()'

# test code
script:
  - R -e "source('popstest2x2.R'); data;"