language: R
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

# install dependencies
addons:
  apt:
    packages:
      - R

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

# test code
script:
  - R -e "source('popstest2x2.R'); data;"