language: R
cache: packages
sudo: false
dist: trusty

env: _R_CHECK_CRAN_INCOMING_=FALSE


matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: 3.5
      after_success:
        - Rscript -e 'covr::codecov()'
    - r: devel

r_packages:
  - covr
  - devtools
  - raster
  - rgdal
  - Rcpp

after_success:
  - Rscript -e 'library(covr); codecov()'