language: R
cache: packages
sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

matrix:
  include:
    - r: 3.3
    - r: 3.4
    - r: 3.5
    - r: devel

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev
  - sudo apt-get install libudunits2-dev
  - sudo apt-get install libssh2-1-dev
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'
  - Rscript -e 'update.packages(ask = FALSE)'

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"

env: 
  global:
      - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

after_success:
  - Rscript -e 'library(covr); codecov()'